hexagon-dsp-binaries: remove from RDEPENDS the version operator
opkg without the libsolve doesn't like it and fails:

error: calculate_dependencies_for: Cannot satisfy the following dependencies for packagegroup-base-extended:
        linux-firmware-qcom-qcm6490-audio (>= 1:20251011)       linux-firmware-qcom-qcm6490-compute (>= 1:20251011)

Signed-off-by: Jose Quaresma <jose.quaresma@oss.qualcomm.com>