linux-qcom-next: enable namespaces
Container runtimes like docker and podman require namespace support:

  root@rb3gen2-core-kit:~# docker run ghcr.io/koenkooi/test:latest
  WARN[0000] Failed to read current user namespace mappings
  Error: creating network namespace for container 6b7886e1ad19f5cfc86e19ce1d9e26f8ada9bef00fef498750f7593a0325f1f7: failed to create namespace: unshare network namespace: invalid argument

Signed-off-by: Koen Kooi <koen.kooi@oss.qualcomm.com>